config/almostunified/unify.json, kubejs/server_scripts/constants_server.js, kubejs/server_scripts/datapack/override_tfc_armour.js, kubejs/server_scripts/main_server.js, kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/replace.js, kubejs/server_scripts/tags/item_tags.js, kubejs/startup_scripts/main_startup.js, kubejs/startup_scripts/registry/materials.js
All needed changed for the AU re-order, thanks to `Len Kagamine` for helping me with the Armour Override
Rock Breaker has been switched from `event.custom( )` to using the gtceu kjs integration, as the `event.custom( )` was temperary till we could get the adding of rock breaker recipes working with the kjs integration
=> Almost Unified Re-Order and Rock-Breaker switch

kubejs/server_scripts/constants_server.js, kubejs/server_scripts/recipes/tfc_heating.js
Originally the function didn't work for the fluid inputs because it was considered a CreateInputFluid type rather than UnboundFluidStackJS
This converts CreateInputFluid to UnboundFluidStackJS so that it updates the input amount to the correct ratios
=> Fixed the TFC Alloying via. Create Mixer Recipes

kubejs/server_scripts/mods/gtceu/chains/certusBoule.js, kubejs/server_scripts/tags/item_tags.js
Since the Certane chain was migrated from GTCEU to Gregitas_Core it was causing recipes to be non-existent and allowed certus quartz to be made from nothing in chem reactor
=> Fixed Certane Chain recipes and Updated Plate Tags

config/sparestructuresreforged.json, config/sparsetructuresreforged.json
This was causing structures to be excessively common.
Funnily enough, the new file also appears to have a typo, but it truly is "sparsetructures" instead of "sparsestructures"!
=> Fix typo on sparse structures mod

kubejs/server_scripts/tags/item_tags.js
Adds `tfc:blast_furnace_fuel` tag to Coke, Coke Block, Flawless Coke Gem and Exquisite Coke Gem.
This allows you to put vanilla Coal and TFC Bituminous Coal into a Coke Oven and use the output for the TFC Blast Furnace. I do not know why you would use Coke Block or Flawless Coke Gem (mostly kept them because they have the Forge Fuel tag). 
This makes the TFC Blast Furnace as a more viable alternative to the GT Primitive Blast Furnace. 
I personally really like the TFC Blast Furnace over the GT one, but it is really annoying to use since it requires a huge amount of Charcoal to use. I need wood for all kinds of things, but I have stacks and stacks of vanilla coal (exploration + wither skeletons) and bituminous coal laying around unused.
=> Adds coke to blast furnace recipe

config/gtceu.yaml
Turned on a variety of gregtech hardmode recipes. Namely gregified recipes of certain items. Of greatest interest will be that crafting rods in an extruder is now more efficient than in a lathe and recipe times reset if the machine loses power (no more playing on and off with the machine's power switch).
There may be cleanup to occur over time to bring recipes from other mods in line with the gregification of vanilla items such as doors, trapdoors, bookshelves, etc.
=> Gregtech Config Settings Update

config/almostunified/unify.json, kubejs/data/firmalife/recipes/crafting/bacon.json, kubejs/data/firmalife/recipes/crafting/salsa.json, kubejs/data/firmalife/recipes/crafting/tortilla_chips.json, kubejs/data/tfc/recipes/barrel/fresh_to_salt_water.json, kubejs/server_scripts/mods/create/createAdd.js, kubejs/server_scripts/tags/item_tags.js
- Unifies GTCEU Salt Dust and TerraFirmaCraft Salt.
- Rebalances the TFC Saltwater in barrel recipe to use the GTCEU amounts (500mB water + 1 salt dust -> 500mB salt water)
- Unifies GTCEU Saltpeter, Railcraft Reborn saltpeter, and TFC Saltpeter.
- Re-tags Railcraft saltpeter which was mistakenly called "salt"
Issues:
1. TFC Salt still spawns in-world as the salt lick blocks. Could further unify with KubeJS or something but I decided to hold off for now as it's a large change compared to how much it actually impacts. TFC Salt should be interchangeable with the GTCEU Salt dust for all recipes anyway but still needs comprehensive testing.
2. Did not touch the 2x salt + sulfur + charcoal gunpowder recipe, but it's really odd to do this with NaCl salt.
3. Allows for infinite TFC salt starting …
=> Unify GT Salt and TFC Salt (And salt/saltpeter audit)

kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/removal.js
See also related post in discord forum:
[HPCA recipe is broken due to reduced stack size](https://discord.com/channels/254530689225981953/1290385510023299222/1290385510023299222)
Basically HPCA recipe requires 64 wires to be stored in a single ULV input bus, which is impossible due to wire stack size reduced to 32.
This changes the recipe to 2 stacks of 32 wires so it can be crafted.
Currently blocking the progression because anything later in zpm/uv requires a functional research station.
=> Fix HPCA recipe

kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/removal.js, kubejs/server_scripts/recipes/replace.js
This changes:
- Fixes wire stack limit for ultimate battery recipe (from 64 to 2x 32)
- Allow some computer recipes to accept any LV circuits instead of only `Basic Electronic Circuit` (It doesn't make sense when recipes like Computer already accept any LV circuits)
PS.
Is it okay to remove a recipe in removal.js and add it back with the same recipe id in add.js?
I'm not sure if that's a safe thing to do so I changed the recipe id from `ultimate_battery` to `uhv_battery`.
=> Fix recipes for ultimate battery and computercraft stuff

kubejs/server_scripts/tags/item_tags.js
Create Diesel Generator's adds a Wood Chips item. This is in essence, wood dust, though it is not tagged as such. This change set adds the appropriate tags to it.
=> feat: tag wood chips as wood dust

kubejs/server_scripts/tags/item_tags.js
The Create: More Drill Heads mod adds its own quartz dust. This quartz dust is tagged with forge:dusts/quartz, but not forge:dusts/nether_quartz which is what gtceu expects. This PR ensures that both dusts are tagged with the same tags.
=> feat: ore-dicting create drill mods quartz dust with gtceu quartz sand

config/ftbquests/quests/chapters/medium_voltage.snbt
This is a fix for: https://discord.com/channels/254530689225981953/1303089174420914216
=> fix: make clayline quest return tfc diorite

config/ftbquests/quests/chapters/railcraft.snbt
This PR ensures that the user is not given vanilla gravel as a quest reward, and is instead given a tfc gravel.
=> fix: replace the vanilla gravel quest reward from railcraft tank quest

kubejs/server_scripts/tags/item_tags.js
fixed a simple typo that's breaking dev
=> fix: fix typo in scguns niter dust tagging

kubejs/server_scripts/mods/create/createAdd.js
This PR adds the ability to crush mossy cobble down to gravel, and 20% change of a plant ball. The 20% is a halfway point in between the 30% of a grass block, and 12.5% of a dirt block.
=> feat: added crusher recipe for mossy cobbles

kubejs/server_scripts/tags/item_tags.js
Add forge coal coke tags to gt coke to be able to grind it into graphite
=> feat: add coke tags to gt coke for create crushing

kubejs/server_scripts/recipes/removal.js
This disables the charcoal pile igniter which is currently broken due to needing vanilla dirt, and logs. It also goes against the TFC charcoal process so it is being disabled.
Additionally this PR also disables the treated iron bucket recipe which is an unintended technology skip as it allows you to craft a bucket without getting a GT bender.
=> fix: disable charcoal pile igniter, and treated iron bucket recipes

kubejs/server_scripts/recipes/tfc_heating.js
Currently players can craft plates via a bender or create press, and then craft a double plate from that. They then take the double plate (which only cost two ingots), and craft a tuyere which can then be melted down for four ingots. This PR adds the tuyere to the list of items that have their outputs halved.
=> fix: remove tfc tuyere dupe

config/ftbquests/quests/chapters/railcraft.snbt, kubejs/assets/gravitas/lang/en_us.json
This PR adds two new quests to the railcraft chapter. Both quests are for the railcraft multiblock iron tank, and steel tank respectively. The completion of the iron tank quest returns 8 iron ingots, while the steel tank quest returns 8 steel ingots. The reward is a bit arbitrary, but I opted to give some raw resources back that went into the construction of the tanks.
=> feat: added railcraft tanks quests

kubejs/data/treetap/recipes/menril_resin.json
This PR adds support for tapping menril resin from menril trees. The schedule, and rate is identical to the kapok tree resin tapping.
=> feat: added tree-tap support for menril resin

kubejs/server_scripts/tags/fluid_tags.js
This allows olive oil to be used as a plant oil when interacting with non-tfc mods.
=> feat: add olive oil as a plant oil

kubejs/startup_scripts/registry/machines.js
This change allows for air to be used in addition to saplings for the center of a greenhouse. This means that this change is fully backwards compatable.
=> feat: allow for greenhouse to have air instead of sapling

kubejs/server_scripts/recipes/removal.js
in general we rely on GT alloy furnace, and compressor recipes for ingot blocks. This PR removes a thoriumreactor mod caused exception to this where you can use a 3x3 crafting table to craft titanium blocks
=> feat: remove 3x3 titanium block recipe

kubejs/data/treetap/recipes/menril_resin_from_menril_log.json, kubejs/data/treetap/recipes/menril_resin_from_menril_log_filled.json, kubejs/server_scripts/tags/block_tags.js, kubejs/server_scripts/tags/fluid_tags.js
This PR does a bit more work on the menril resin tree tap work. I added support for filled logs. 
One thing to note is that these changes here (and in the last resin PR) don't fully work until I get a PR merged over in the treetap mod
Right now the recipe exists in NEI, but the tap just isn't attachable to a menril log
=> chore: clean up menril resin

kubejs/data/treetap/recipes/crimson_resin_from_crimson_log.json, kubejs/data/treetap/recipes/warped_resin_from_warped_log.json, kubejs/startup_scripts/registry/fluids.js
This PR adds both crimson resin, and warped resin. They are both extracted from their respective nether tree. 
This PR does not contain any uses of said resin, that will come in a follow up PR.
=> feat: add nether tree resins

kubejs/server_scripts/recipes/add.js
Added a recipe for centrifuging crimson resin. It's yields are 60% of centrifuging netherrack, and the processing time, and energy usage are identical.
=> feat: added basic nether resin centrifuging recipes

config/ftbquests/quests/chapters/gravitaschaptersnew3title.snbt
The wrong saltpeter was being used.
=> fix: correcting saltpeter type in salt or seaweed quest

kubejs/data/gtceu/recipes/brewery/tfc_compost_greens.json, kubejs/data/gtceu/recipes/brewery/tfc_compost_greens_high.json, kubejs/data/gtceu/recipes/brewery/tfc_compost_greens_low.json
This PR allows for tfc compostable to be used in the brewery for biomass. Weak compost produces equivalent to the smallest pre-existing biomass recipe, while high produces the equivalent of the largest existing biomass recipe.
=> feat: added brewery recipes for tfc green compostables

kubejs/server_scripts/recipes/add.js
This PR adds the two beneath saplings as options to the greenhouse. Instead of taking  MV energy like the other sapling recipes they take HV energy. Additionally instead of consuming water, they consume nether air.
=> feat: added greenhouse recipe for beneath trees

kubejs/server_scripts/mods/ae2/gregifyAE2.js
All recipes using the old digital interface cover now use the new storage cover.
=> Fixed recipes using remove gtceu covers

kubejs/server_scripts/tags/item_tags.js
Phosphor and Phosphorus are not the same thing, however I think its just a naming issue over in scguns (Phosphor just glows, and isn't useful in a firearm themed mod)
This PR tags the scguns phosphor as phosphorus, and additionally lints the file containing the changes.
=> feat: tag scguns phsophor as phosphorus

config/ftbquests/quests/chapters/gravitaschaptersnew2title.snbt
This PR just ensures that the chisel quest supports all tagged chisels, not just copper and vanilla bronze (this is primarily to support stuff like black bronze chisels).
=> feat: support all chisels in chisel quest

kubejs/server_scripts/recipes/removal.js
This PR removes the ability for smelting, and blasting menril logs into charcoal. I am assuming this is unintentional, as every other variety of logs must go through explicit processes instead of just being cooked in the way that vanilla logs are.
This PR also applies the linter to the removal.js file.
=> feat: remove ability to smelt menril logs to charcoal

kubejs/data/tfc/recipes/welding/cobalt_brass_double_ingot.json, kubejs/data/tfc/recipes/welding/damascus_steel_double_ingot.json, kubejs/data/tfc/recipes/welding/tungsten_carbide_double_ingot.json, kubejs/data/tfc/recipes/welding/tungsten_steel_double_ingot.json, kubejs/data/tfc/recipes/welding/ultimet_steel_double_ingot.json, kubejs/data/tfc/recipes/welding/vanadium_steel_double_ingot.json
Added tfc welding recipes for gregitas double ingots. This helps users who have found ingots like damascus steel in a temple use it to make things like mortar&pestles.
=> feat: added tfc welding recipes for gregitas double ingots

kubejs/server_scripts/recipes/removal.js
Remove the ability to craft a number of vanilla resource (so technically uncraftable) using train tracks due to existence of tfc alternatives. 
This PR does not fix the broken crafting recipes for things like bamboo, stripped bamboo, blackstone, warped, and crimson tracks.
=> feat: remove uncraftable vanilla create track recipes

kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/removal.js
this PR buffs locometal to be produced at a ratio comparable to industrial iron. It removes the old recipe, and adds a new one that uses iron ingots instead of iron blocks, similar to the usage of wrought iron with industrial iron block production.
=> feat: make locometal cheaper

kubejs/server_scripts/recipes/replace.js
This PR fixes the tier 2 compacting drawer requiring vanilla stone instead of forge stone (tier 3 was already correctly handled), and the reliance on uncraftable vanilla drawers.
=> feat: fix storagedrawers relying on vanilla items

config/ftbquests/quests/chapters/create_brass_stage.snbt, config/ftbquests/quests/chapters/gravitaschaptersnew3title.snbt, config/ftbquests/quests/chapters/gravitaschapterssteamtitle.snbt, config/ftbquests/quests/chapters/low_voltage.snbt, kubejs/assets/gravitas/lang/en_us.json
-Change the amount of the mechanical crafter quest to match the size needed to make crushing wheels
-Replaced quest on the chapter 3 related to the crushing wheels and mechanical crafter with links of the same quest on the create braze age chapther
-Change quest that needed create sand paper to tag filter create:sandpaper
-Change your first LV-Circuit quest to be dependant on 3x Basic Electronic Circuits
-Added mention for water tank and primitive pumps on the steam boiler quest
-Added mention of criolite on red alloy quest as another source of redstone
-Added quest for miner at steam age 
-Change the quest for the basic mixer to also alloy the basic kinetic mixer
-Added quest for steam multiblocks (grinder and oven)
-Added quest for the greg tech terminal
=> Quest Work

kubejs/server_scripts/tags/item_tags.js
Set `refreshGTMaterials` to true to generate a new json when needed (you need NOW, as this will be your first run)
=> fix: use static json instead of querying at runtime

kubejs/server_scripts/recipes/add.js
This recipe was missing, which seems like an oversight. Both normal tin bronze and black bronze can be pressed into corresponding plates with a Create press, so this brings bismuth bronze in line with that.
=> Adds bismuth bronze plate to Create press

kubejs/server_scripts/recipes/add.js
Belt Grinder (from Vintage Improvements) can now process uncut TFC gems into their cut variants. This includes processing Kimberlite into diamonds.
Previously, Belt Grinder was only useful for making Rose Quartz into Polished Rose Quartz. I plan on adding more recipes to it, but that's going to happen in other PRs.
=> Allows Belt Grinder to cut TFC gems automatically

kubejs/client_scripts/jei_hide/removals.js, kubejs/data/vintageimprovements/advancements/iron_spring.json, kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/coilingTweak.js
Spring Coiling Machine from Vintage Improvements now makes Gregtech springs - making it usable in this modpack.
All Vintage Improvements springs are now uncraftable, and Vintage Improvements machines now use equivalent Gregtech springs.  Spring recipes are copied directly from Gregtech - thus, one long rod produces a single large spring, and one small rod produces two small springs.
The machine itself can now be crafted with just Wrought Iron ingots - same as Create press.
=> Makes Spring Coiling Machine produce Gregtech springs

kubejs/data/beneath/beneath/nether_fertilizers/small_sulfur_dust.json, kubejs/data/beneath/beneath/nether_fertilizers/sulfur_dust.json
Beneath book says that sulfur is a valid Flame + Decay fertilizer, but the mod itself only applies those properties to TFC sulfur powder - which is fully replaced by Gregtech sulfur dust in this modpack.
This PR adds the same fertilizer properties to Gregtech sulfur dust, as well as small sulfur dust (at 1/4 the strength).
=> Makes Gregtech sulfur a valid fertilizer for Beneath crops

kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/pressurizedBasinAdd.js
Basin with a Basin Lid (from Create Diesel Generators) can now run GT Autoclave recipes. You need to close the lid and heat the basin for it to work.
Basin needs to be at "heated" for LV level recipes, and at "superheated" for MV level recipes (there's just one MV autoclave recipe). Recipes above MV level are unavailable.
=> Makes Create basin with a lid run some Gregtech Autoclave recipes

config/jei/recipe-category-sort-order.ini, kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/wiresAdd.js
You can now make Gregtech 1x wires by processing metal rods in Rolling Mill (from Create Additions). And you can make cables too by spraying wires with molten rubber from a Create spout.
Even the wires that need plastic sheets can be made with a Create assembly sequence. Is it practical? Not really. But it would be cool to see someone pull it off!
=> Allows Gregtech wires and cables to be made with Create

config/ftbquests/quests/chapters/gravitaschaptersnew2title.snbt, config/ftbquests/quests/chapters/medium_voltage.snbt, kubejs/assets/gravitas/lang/en_us.json, kubejs/client_scripts/jei_add.js, kubejs/client_scripts/jei_hide/removals.js, kubejs/client_scripts/main_client.js, kubejs/server_scripts/mods/create/createAdd.js, kubejs/server_scripts/mods/gtceu/gtceuAdd.js, kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/removal.js, kubejs/server_scripts/recipes/replace.js, kubejs/server_scripts/tags/item_tags.js, kubejs/startup_scripts/constants_startup.js
Feel free to review commit-by commit, rather than the whole thing at once.
- Add recipe + unhide framed double slab/panel 
- Hide ID squeezers
- Fix create connected fluid vessel needing vanilla barrel
- Vanilla book/quill now only needs black dye
- Glow inc bulk haunting now only needs black dye
- TFC saltpeter powder recipe fixes
- Misc mv quest fixups
- TFC salt water to salt heated mixing (worse efficiency than centrifuge)
- TFC stripped **wood** create sawing recipes
- TFC supports create sawing recipes (stripped logs only)
- Wrought Iron Ingots use Create superheated pressing (brilliant white), rather than NBT fIxes #480 
- Railcraft steel anvil uses solidifier
- Hid many unobtainable items (also removed their tags so they don't show in recipes, nice qol change)
- Unified immersive …
=> More misc tweaks :)

kubejs/data/tfc/recipes/alloy/battery_alloy.json, kubejs/data/tfc/recipes/alloy/cupronickel.json, kubejs/data/tfc/recipes/alloy/potin.json, kubejs/data/tfc/recipes/alloy/potin_bronze.json, kubejs/data/tfc/recipes/alloy/soldering_alloy.json, kubejs/data/tfc/recipes/alloy/tin_alloy.json
This adds recipes for the following early game Gregtech alloys to TFC, making them available in vessels and crucibles:
* Potin (two recipes, one is basic, another allows for bronze to be recycled into potin)
* Soldering alloy
* Tin alloy
* Battery alloy
* Cupronickel (a bit tricky to make because of an overlap with Constantan - either add more than 60% copper, or melt an existing Cupronickel ingot to force it)
=> Adds TFC recipes for a few early game Gregtech alloys

kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/materialProcessing.js, kubejs/server_scripts/recipes/add.js
This adds plate pressing (Create press) and rod rolling (Crafts and Additions rolling mill) recipes for pretty much every metal added by Gregtech.
It's good for consistency, and it makes early game Create workshops a bit more powerful.
=> Makes Create machines produce Gregtech rods and plates more consistently

kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/advancedRecipes.js, kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/tags/item_tags.js
This makes Create stuff easier to make and automate at LV to MV, and also makes Create more interconnected with Gregtech.
New recipes:
* Rose Quartz can be smelted in Gregtech Alloy Smelter - this uses just 4 redstone, down from 8 you need for manual crafting
* Create belts, tunnels, pulleys and funnels can be crafted using Gregtech rubber sheets in place of kelp/leather
* Create tunnels and funnels can also be crafted using Gregtech rubber/plastic thin sheets
* Create spout can be crafted using Gregtech rubber rings
* Brass tunnels and funnels that use Gregtech rubber can also use Gregtech ULV circuits instead of the Create electron tube
* Chain drives can be crafted using 2x TFC wrought iron chains instead of 3x iron nuggets 
* This adds up to 18mb of wrought iron instead of 48mb of …
=> Adds new recipes for making Create items using Gregtech materials

kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/sulfuric_acid.js
Sulfuric Acid recipe chain from Vintage Improvements now uses Gregtech intermediates and products. You can mix and match it with Gregtech freely.
This also allows for Vintage Improvements sulfur to be ground down into the usual sulfur dust - like every other type of raw sulfur in this modpack.
=> Makes Vintage Improvements recipe chain for Sulfuric Acid compatible with Gregtech

config/createdieselgenerators-server.toml
This PR adds a Diesel Generators config, and bumps the default canister capacity up - from 4 buckets to 32 buckets. It also bumps up the capacity gain from enchanting - to 64 buckets per enchantment level.
Even a fully enchanted canister is still inferior in capacity to GregTech drums, and can't auto-output. And in early game, bronze drums have the same capacity, and are easier to obtain. This just makes it so those canisters don't completely suck.
=> Bumps Diesel Generators canister capacity up

kubejs/server_scripts/mods/gtceu/gtceuAdd.js
Instead of a mallet, the crafting recipe now uses a file. It can also use beeswax or Create glue tube instead of resin. This allows for slightly earlier Coke Oven automation.
Not a big change, mostly just consistency with #466 - which changed GregTech wood pipes from mallet to file to make them available a bit earlier.
=> Makes GregTech wood barrels available earlier

kubejs/server_scripts/datapack/parts_heating_recipes.js, kubejs/server_scripts/main_server.js
Adds TFC heating recipes to make many parts resmeltable in the forge/crucible/basin
- Melting temperatures = as per TFC mod files or as GT Kelvin temperature of fluid converted to °C.
- Heating capacities of metals are per mb and are multiplied by the mb resmelt value of a part to get the part's heating capacity. Capacities of each metal are based on the capacity of an ingot of that metal / 144 or = to iron if not found.
- Metal liquids are the same as what would normally be produced by TFC forge.
- All types of iron smelt back to cast Iron. The forge can't be used to get wrought or purified iron.
- Magnertic/energized metal items of any kind revert to regular molten metal.
- Liquid amounts are set to equal the converted value of the cheapest available recipe or the amount produced by GT …
=> Add many parts heating recipes

kubejs/server_scripts/mods/ae2/gregifyAE2.js
* Adds recipes for more consistency between recipes in AE2 itself, GregTech and Create
* Painting AE2 cables and coating AE2 cables in resin can now be done with Create hardware
* Makes AE2 recipes use both nether quartz and overworld quartz (TFC+IE geodes) more consistently
* Moves all GregTech dye recipes into a new Chemical Dyeing recipe subcategory for better organization
This doesn't add any new progression or skips. It doesn't allow to access AE2 earlier than you otherwise could have.
=> Improves AE2 recipe consistency

kubejs/server_scripts/main_server.js, kubejs/server_scripts/mods/create/oreVibratingAdd.js
Makes another Create machine more useful.
Sifter recipe outputs are chance based, and chances improve with tiers. So GregTech sifters are better at MV+.
=> Allows Vibrating Table to run LV Sifter recipes

kubejs/server_scripts/recipes/add.js, kubejs/server_scripts/recipes/removal.js, kubejs/server_scripts/tags/item_tags.js
- Removes the `forge:purified_ores/naquadah` item tag from `sgjourney:pure_naquadah`
- Replaces the recipes for the following items:
- `sgjourney:classic_stargate_base_block`
- `sgjourney:classic_stargate_chevron_block`
- `sgjourney:classic_stargate_ring_block`
- `sgjourney:classic_dhd`
- `sgjourney:pure_naquadah`
- `sgjourney:crystal_base`
- `sgjourney:materialization_crystal`
- `sgjourney:control_crystal`
- `sgjourney:transfer_crystal`
- `sgjourney:communication_crystal`
Stargates are effectively gated to GT's LuV age as well as having access to The Other
=> Stargate recipe update
