AllTheMods/Gravitas2

- defaultconfigs/tfc-server.toml
Updated the capacities of the molds and the crucible so it matches the changes of 1 ingot now being 144mb
> Change Mold and Crucible capacities in the Configs

- kubejs/data/gtceu/tfc/item_heats/metal/invar_ingot.json
- kubejs/data/gtceu/tfc/metals/invar.json
- kubejs/data/tfc/recipes/alloy/invar.json
- kubejs/data/tfc/recipes/anvil/invar_plate.json
- kubejs/data/tfc/recipes/casting/invar_ingot.json
- kubejs/data/tfc/recipes/heating/metal/invar_double_ingot.json
- kubejs/data/tfc/recipes/heating/metal/invar_ingot.json
- kubejs/data/tfc/recipes/welding/invar_double_ingot.json
- kubejs/data/tfc/recipes/welding/invar_double_plate.json
- kubejs/data/tfc/tfc/item_heats/metal/invar_double_ingot.json
- kubejs/data/tfc/tfc/item_sizes/metal/invar_double_ingot.json
- kubejs/server_scripts/gtceu/tags.js
- kubejs/startup_scripts/registry/items.js
Custom invar recipes using tfc crafting methods
> Invar Recipes

- kubejs/startup_scripts/registry/items.js
> double ingot fix

- kubejs/server_scripts/datapack/greg_vein_maker.js
- kubejs/server_scripts/main_server.js
- kubejs/server_scripts/tags/greg_vein_tags.js
Makes and tags TFC veins for world generation customization
Includes example and instructions, at least until someone can work on the greg-render-crash issue.
> Simple Vein Maker

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/removal.js
- kubejs/server_scripts/recipes/replace.js
- kubejs/server_scripts/tags/item_tags.js
Create gears, and less leather cheese.
> Progress on things

- kubejs/server_scripts/datapack/greg_ingots.js
- kubejs/server_scripts/recipes/add.js
ctetrahedrite
ingregients.
oops.
> Fixes spelling moment in 2 scripts causing errors.

- kubejs/server_scripts/datapack/greg_ingots.js
- kubejs/server_scripts/recipes/tfc_heating.js
- kubejs/startup_scripts/forge_events/tfc_ingots.js
> Fix equality, add double ingots, added .save() to recipes

- kubejs/server_scripts/constants_server.js
my bad i forgot to include the server constants
> Constant Hot Fix

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/removal.js
remove some unwanted woodencog recipes, railcraft cheesy bronze craftin and adds treetap recipe, removes some create recipes , swaps resin production to resin tapped from kapok, adds maple sap, and recipes for sap to syrup  and resin to sticky resin
> recipe changes

- kubejs/client_scripts/main_client.js
- kubejs/client_scripts/tooltip/circuits.js
Added Circuit Tooltips to help tell the differences between the circuits
> Circuit Tooltips

- kubejs/server_scripts/recipes/gtceu_tools.js
fixed missing recipe for wrench claw
> fix wrench recipe

- kubejs/server_scripts/mods/create/createAdd.js
- kubejs/server_scripts/recipes/gtceu_tools.js
switched around the order of the gregtech tools in anvil to make it match the default TFC order
> Anvil order( issue #75 )

- kubejs/server_scripts/tags/item_tags.js
> tool rack tags

- kubejs/server_scripts/tags/item_tags.js
This includes all stone slabs, including ones that don't match the color scheme, im sure this is fine and won't appear in future arguments
> Added sleeper tag to all tfc smooth stone slabs

- kubejs/server_scripts/recipes/replace.js
Up the amount accordingly
Normal from 1 to 6
Narrow from 1 to 3
> Up the amount of Railways tracks

- kubejs/server_scripts/recipes/removal.js
> Removed leather recipe from ID drying basin

- kubejs/client_scripts/main_client.js
- kubejs/client_scripts/tooltip/create_style.js
Adds a Create style tooltip to the following:
- Lightning Dragon Spawn Egg
- Fire Dragon Spawn Egg
- Ice Dragon Spawn Egg
- Hippogryph Spawn Egg
- Cyclops Spawn Egg **(NYI)**
- Amphithere Spawn Egg **(NYI)**
- TFC Snowberry Bush
- TFC Bunchberry Bush
- TFC Gooseberry Bush
- TFC Cloudberry Bush
- TFC Strawberry Bush
- TFC Wintergreen Bush
- TFC Cranberry Bush
- TFC Blackberry Bush
- TFC Raspberry Bush
- TFC Blueberry Bush
- TFC Elderberry Bush
- TFC Cherry Sapling
- TFC Green Apple Sapling
- TFC Apple Sapling
- TFC Lemon Sapling
- TFC Olive Sapling
- TFC Orange Sapling
- TFC Peach Sapling
- TFC Plum Sapling
- TFC Banana Sapling
- TFC Red Apple Sapling
- Firmalife Nightshade Bush **(Unknown)**
- Firmalife Pineapple Bush **(Unknown)**
- Firmalife Fig Sapling **(Unknown)**
- Firmalife Cocoa …
> Additional tooltips

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/gtceu_tools.js
- kubejs/server_scripts/tags/item_tags.js
Doesn't have any new any_bronze recipes
> Tweak to Gravitas Any bronze Tags

- kubejs/server_scripts/recipes/add.js
Update to ore dict lv circuits for SFM manager recipe. Hope it's in the dev branch this time.
> SFM Manager Recipe Update

- kubejs/server_scripts/recipes/add.js
Balanced to be completed by a player that is well into EV. 
Multi block and decorative block recipes are not yet changed at this point.
> Replace All Thorium Reactor Machine Recipes with EV GT Machine recipes

- kubejs/server_scripts/recipes/add.js
Minor recipe tweaks and recipes for turbine and heatsink multiblock parts
> Thorium Reactors Phase 4 edits

- kubejs/server_scripts/mods/ae2/gregifyAE2.js
- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
- kubejs/server_scripts/recipes/replace.js
i didnt meant to make the coal coke and extended ae the same pr but whatever
> Add lignite -> coke back, also gregify extendedae

- config/gtceu.yaml
Reverts AllTheMods/Gravitas2#244 because it was pointed at the wrong branch
> Revert "Gregtech Config Settings Update"

- kubejs/server_scripts/recipes/add.js
make brick recipe in alloy smelter better for early on, fixed a typo for thorium reactors electromagnetic coils
> improve brick recipe, and fix a typo

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/removal.js
Make straw hat recipe match classic helmet recipes, and no longer conflict with thatch slab recipe
> Fix 251 - change straw hat recipe

- kubejs/server_scripts/mods/create/createAdd.js
Adds in recipes to produce olive oil using Create. Has the same item/fluid amounts as the TFC recipes.
> Create olive oil recipes

- kubejs/server_scripts/recipes/add.js
> miscalculated a recipe

- kubejs/startup_scripts/registry/machines.js
Combined the input fluid slot capacity into one
> Fix for automating Certane

- kubejs/server_scripts/recipes/add.js
after in server testing recipe feels to easy too achieve
> nerf pellet recipe

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
Removed the duplicated cobble to gravel recipe and fixed the formatting of gravel to sand (again)
> Deleted duplicate recipe

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/removal.js
Tested in singleplayer, let me know if there's anything wrong.
> Change asphalt block recipe to be compatible with tfc gravel sand types

- kubejs/server_scripts/recipes/replace.js
This is a fix for:
https://discord.com/channels/254530689225981953/13067240771252388154
The end result of this PR is that it is now possible to create a tfc compass in an assembler.
> feat: change vanilla compass recipes to return tfc compass

- kubejs/server_scripts/recipes/add.js
This PR adds more saplings to the greenhouse. The yields are based on a hybrid of crops, and trees.
> feat: add more trees to greenhouse

- kubejs/server_scripts/tags/item_tags.js
This PR ore-dicts tfc coral with the `create:upgrade_aquatic/coral` tag
> feat: ore-dicting tfc coral

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
- kubejs/server_scripts/recipes/add.js
this PR adds extractor, and compressor recipes for the tfc ie crossover ores(uraninite, bauxite, galena)
> feat: macerator and extractor recipes for  tfc crossover

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
This PR allows for tfc plants and crops to be turned into plant balls.
> feat: add plant ball recipe for tfc crops

- config/ftbquests/quests/chapters/high_voltage.snbt
- kubejs/assets/gravitas/lang/en_us.json
* add infinite water cover quest next to steel boiler
* removed neutronium wrench from clean room quest reward
* ensured all hv quests used localization
> feat: added infinite water cover quest, and fixed existing quests

- config/ftbquests/quests/chapters/gravitaschaptersnew1title.snbt
- kubejs/assets/gravitas/lang/en_us.json
* made the initial casting quest accept castings made from any material. This is to support folks finding bronze in a temple, and using that for their first tools.
* added an aqueduct quest that helps inform the user about the existence of aqueducts.
> feat: added aqueduct quest, and generalized initial casting quest

- kubejs/server_scripts/recipes/add.js
This PR adds a press recipe for the black bronze plates using the create press. Additionally if fixes some of the formatting issues in the immediately surrounding areas.
> feat: add create press recipe for black bronze plates

- kubejs/server_scripts/recipes/add.js
This PR does two things, firstly it adds all of the tfc flowers to the greenhouse, secondly it lints the file.
> feat: added tfc flowers to the greenhouse

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
This PR lints the gtceuAdd.js file and adds a double ingot recipes to the create compactor. The double ingot recipe requires flux, and for the basin to be superheated. 
Additionally it adds recipes for crafting the tfc high carbon steels.
> feat: add create double ingot and tfc steel recipes

- kubejs/server_scripts/recipes/add.js
added the ability to crush and macerate tfc dye giving plants, similar to how the plants can already be processed manually using the tfc quern.
> feat: added gt & create dye recipes for tfc plants

- kubejs/server_scripts/mods/ae2/gregifyAE2.js
This PR adds assembler recipes for the three ae2 processors. They use the molten red alloy instead of fine red alloy wire similar to the other gregified recipes.
> feat: added greg recipes for ae2 processors

- kubejs/server_scripts/recipes/replace.js
This PR lints replace.js, and replaces the usage of the minecraft dandelion with the tfc dandelion.
> fix: fixed scguns poultice recipe

- .gitignore
- kubejs/server_scripts/main_server.js
- kubejs/server_scripts/mods/scguns/replaceDisc.js
- kubejs/server_scripts/recipes/replace.js
Changed the gtcu recipes to use glue instead of slime
Changed disc recipes to use PVC
> Slimeball to Glue + Disc recipes

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
- kubejs/server_scripts/recipes/gtceu_tools.js
- kubejs/server_scripts/recipes/removal.js
- kubejs/server_scripts/recipes/replace.js
- kubejs/server_scripts/recipes/tfc_heating.js
https://discord.com/channels/254530689225981953/1318724928991920150
Changed auto weld to use specific item id because it doesn't support multiple tags
Fixed aluminium inconsistency
> Automated Welding Fix

- kubejs/server_scripts/mods/ae2/gregifyAE2.js
> AdvancedAE Gregification

- config/ftbquests/quests/chapters/blast_furnace_to_help_make_a_different_anvil.snbt
- config/ftbquests/quests/chapters/create_beginning.snbt
- config/ftbquests/quests/chapters/gravitaschaptersnew2title.snbt
- config/ftbquests/quests/chapters/gravitaschaptersnew3title.snbt
- config/ftbquests/quests/chapters/gravitaschapterssteamtitle.snbt
-Fix amounts of coke oven bricks and fire bricks on quest Chapter 4 
-Reorganised the create beginning quest chapter
-Change quest for the mechanical mixer and mechanical press before getting the basin 
-Change wrought plates quest to only need on dependency completed 
-Reorganised the quest chapter 3
-Change resing quest on quest chapter 3 to require sulphur 
-Change Kimberlite quest to also ask for sand paper 
-Added quest for raw diamond
-Change diamond quest to only need one dependency completed and added raw diamond quest to dependencies 
-Added link to iron anvil quest on Steam Age quest chapter to better display the need for it on the forge hammer 
-Added dependency to steel bolt quest need steel ingot quest 
-Added dependancy to wooden plank quest need wood pulp 
-Change …
> Questbook Details

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/removal.js
- kubejs/server_scripts/recipes/replace.js
New Recipes for LaserIO
Remove some recipes of LaserIO
Replace iron ingots to iron plates on LaserIO recipes
> LaserIO gregtification

- kubejs/client_scripts/jei_hide/categories.js
- kubejs/client_scripts/jei_hide/removals.js
Hid JEI item entry for:
- Vanilla smoker
- Vanilla furnace
- Vanilla furnace minecart
- Vanilla blast furnace
- Vanilla campfire
- Vanilla soul campfire
- Jumbo Furnace
- GT Wooden Mallet (doesn't fit the theme of this PR lol)
Hid JEI recipe category for:
- Vanilla Blasting (doesn't affect Create Bulk Blasting)
- Vanilla Campfire Cooking
- Jumbo Furnace smelting
> JEI Hide Vanilla Smelting Blocks + Recipe Categories

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
Allows you to automate wool yarn production. Currently you have to manually craft and fire a spindle. And allows you to use jute to get string, allowing you to get wool stuff from plants instead of animals.
> Wool -> Wool Yarn and Jute -> String ULV Compressor Recipes

- kubejs/server_scripts/mods/create/createAdd.js
You can now make paper by pressing wood dust or shredded paper in a Create basin with water - no heating required.
Gregtech chemical bath has the same recipes at ULV tier.
> Allows for paper making with Create

- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/replace.js
- kubejs/server_scripts/tags/item_tags.js
TFC lime and Gregtech quicklime are now the same material, and either can be used in making glass or steel. Same goes for TFC/GT soda ash.
> Unifies quicklime and soda ash between TFC and Gregtech

- kubejs/server_scripts/mods/create/centrifugeAdd.js
- kubejs/server_scripts/mods/create/pressurizedBasinAdd.js
- kubejs/server_scripts/recipes/add.js
- kubejs/startup_scripts/main_startup.js
- kubejs/startup_scripts/schemas/create_diesel_generators.js
- kubejs/startup_scripts/schemas/create_new_age.js
- kubejs/startup_scripts/schemas/createadditions.js
- kubejs/startup_scripts/schemas/vintageimprovements.js
This just allows to add new recipes with KubeJS easier. There are no gameplay changes.
> Adds schemas for recipes from Create addons

- kubejs/server_scripts/mods/create/createAdd.js
- kubejs/server_scripts/recipes/add.js
Adds recipes to Vintage Improvements Belt Grinder:
* Loose stones to bricks
* Raw stones to polished stones
* Raw sandstone to polished sandstone
Depends on #504
> Adds belt grinder recipes for bricks and polished stone

- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
Mostly, I just wanted to move those dyeing recipes to a new GregTech "chemical dyeing" category. But I also made Create capable of those recipes while at it.
> Adds Create dyeing for ender chests

- kubejs/server_scripts/datapack/parts_heating_recipes.js
- kubejs/server_scripts/mods/create/materialProcessing.js
- kubejs/server_scripts/mods/create/wiresAdd.js
- kubejs/server_scripts/recipes/add.js
- kubejs/server_scripts/recipes/replace.js
- kubejs/server_scripts/tags/fluid_tags.js
- kubejs/server_scripts/tags/item_tags.js
* Makes neodymium wire from New Age melt into neodymium
* Fixes a Computercraft advanced wireless modem recipe
* Adds steel plates back to the Create press
* Hopefully fixes some of the mess with "flowing oil" not being processable
> Small recipe fixes

- kubejs/data/tfc/tfc/fertilizers/bastnasite.json
- kubejs/data/tfc/tfc/fertilizers/rock_salt.json
- kubejs/data/tfc/tfc/fertilizers/saltpeter.json
- kubejs/server_scripts/mods/gtceu/gtceuAdd.js
- kubejs/server_scripts/recipes/add.js
Last minute tweaks!
* Fixes colored steel GT ingots being impossible to quench in a barrel
* Adds recipes for converting a few TFC ores into GT crushed ores (using macerator at MV)
* Adds TFC fertilizer properties to a few GT materials
* Adds fire clay mixer recipes to Create and GT (115% yield with Create mixer, about 130% with GT at LV mixer)
* Adds recipes for TFC chains to GT Assembler (4x rings -> 16x chains, same yield as TFC if you can get the rings from an extruder)
> More small changes and fixes

- config/ftbquests/quests/chapters/extreme_voltage.snbt
- config/ftbquests/quests/chapters/gravitaschaptersnew3title.snbt
- config/ftbquests/quests/chapters/high_voltage.snbt
- kubejs/assets/gravitas/lang/en_us.json
HV quest got a glow-up. The quest tree is now more interconnected and more steps are described in detail.
This also adds a "skip" to Chapter 3: if you get an EBF capable of making red/blue steel, you can bypass the part where you make weak red/blue steels altogether.
> HV quest improvements
